<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pt</string>
		<string>cpt</string>
		<string>zpt</string>
	</array>
	<key>name</key>
	<string>ZPT</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.zpt</string>
	<key>uuid</key>
	<string>EA7F3BDB-EE02-4789-9424-5F6AD0AF69CF</string>
</dict>
</plist>
